version: 2.1

executors:
  docker-alpine:
    docker:
      - image: alpine:3.15
    resource_class: medium
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /root/project/keys/gcp_sa.json


jobs:
  install:
    executor: docker-alpine
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 48:d2:7e:0a:67:86:04:52:ec:84:33:3a:ee:72:ec:9e
      - run:
          name: "Install softwares"
          command: "apk add --no-cache ansible terraform jq openssh-client"
      - run:
          name: "Copy keys"
          command: |
            mkdir keys
            echo $VAULT_SSH_PUBLIC_KEY > /root/project/keys/id_rsa.pub
            echo $GCP_SERVICE_ACCOUNT > /root/project/keys/gcp_sa.json
      - run:
          name: "Terraform apply"
          command: |
            cd terraform
            terraform init
            terraform apply -auto-approve
      - run:
          name: "Update Ansible inventory"
          command: |
            cd terraform
            terraform output -json ansible-inventory | jq -r '.[]' > ../ansible/inventory
      - run:
          name: "Run Ansible playbook"
          command: |
            ansible-playbook -v -i ansible/inventory ansible/playbook.yaml

workflows:
  workflow:
    jobs:
      - install
